name: Stenback
favicon: null
layout_spectrum: 0.7764893902931362
typography_spectrum: 0.8183460058644414
title: "Mark Stenbäck's Personal Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8185311604756862
  lightness: 0.17610147572122514
  saturation: 0.855486235814169
  rhythmicContrast: 0.30838308203965425
purpose: []
